### PR TITLE
add readme

### PR DESCRIPTION
**Pull request by nickdesaulniers**
something simple to get the ball rolling.  Please correct any inaccuracies.  This was written up quickly based on my limited understanding.

### CODE REVIEW

**Review by xerpi — APPROVED** [review]
Looks good to me, much better than no README!

**Comment by nickdesaulniers** [comment]
updated with license info

**Comment by nickdesaulniers** [comment]
I should probably clarify PXI based on: https://www.reddit.com/r/3dshacks/comments/6iclr8/a_technical_overview_of_the_3ds_operating_system/

**Comment by nickdesaulniers** [comment]
also: https://www.youtube.com/watch?v=bZczf57HSag&t=330s has a nice overview of PXI and confirms arm9 access to sd card.

**Comment by xerpi** [comment]
I think ARM11 can also access the SD directly, without having to go through PXI and communicate with ARM9.
Check: https://www.3dbrew.org/wiki/CONFIG9_Registers#CFG9_SDMMCCTL

**Comment by nickdesaulniers** [comment]
ok, how does that read now, @xerpi ?

**Comment by xerpi** [comment]
Looks good!
We can always tweak it later, but at least we have a baseline :)

**Comment by Wolfvak** [comment]
just to clarify the ARM11 & SD things: the 3DS has 3 SD controllers (unlike the DSi which only has 2), each with up to 4 ports.

controller 1 can access the internal NAND on port 1 and depending on a configuration register, it can multiplex SD access with controller 3 on port 0. this controller is also mappable to a region accessible to the ARM11, and is connected to the interrupt distributor.
controller 2 is only connected to the wifi chip. it is also _only_ connected to the ARM11.

one way or another, to access the NAND we must go through the ARM9, so I decided to expose that via the virtio bridge and let the ARM11 handle the wifi chip (eventually). there was a test where linux could successfully access the SD card and send raw SDC commands to it, but it's useless for accessing the NAND and that's kinda necessary if you ask me

**Pull request merged**
