### PR TITLE
Docker build

### PR DESCRIPTION
**Pull request by kleo**
Instructions for building with Docker environment included in README.md

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
cool, thanks!

I don't like the inconsistency between instructions for Docker, vs some on the wiki https://github.com/linux-3ds/arm9linuxfw/wiki.  How about you point people to the wiki from the readme, then update the readme after the Dockerfile lands?

**Comment by kleo** [comment]
I removed the instructions on readme. You can add them on wiki or you can let me write it for you

**Review by nickdesaulniers — APPROVED** [review]
SGTM, are you able to edit the wiki or do we need to add you to the org?

**Comment by nickdesaulniers** [comment]
@Wolfvak can help with org invites

**Comment by kleo** [comment]
> SGTM, are you able to edit the wiki or do we need to add you to the org?

I think you need to add me to the org

**Pull request merged**
